main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('login/', views.login_user, name='login_user'),
    path('about_us/', views.about_us, name='about_us'),
    path('<int:products_id>/', views.product_detail, name='product_detail'),
    path('', views.index, name='index'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('', views.all_products, name='all_products'),
    path('group/', views.product_group, name='product_group'),
    path('add_product/', views.add_product, name='add_product'),
    path('thanks/', views.thanks, name='thanks'),
    path('edit_product/<int:id>/', views.edit_product, name='edit_product'),
    path('delete_product/<int:id>/', views.delete_product, name="delete_product"),

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', include('main.urls')),
    # path('about_us/', include('main.urls')),
    # path('add_product/', include('products.urls')),
    # path('thanks/', include('products.urls')),
    # path('edit_product/', include('products.urls')),
    
]

main/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
# from products.models import Product


class Product(models.Model):
    title = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2, max_digits=6)
    description = models.TextField(null=True, blank=False)
    quantity = models.PositiveIntegerField(default=0, blank=True)
    group = models.ForeignKey('products.Group', on_delete=models.PROTECT, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title} : {self.price} : {self.description}'


class Group(models.Model):
    title = models.CharField(max_length=100, unique=True)
    code = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return f'{self.title} : {self.code}'

main/forms.py
from django import forms


class Login_form(forms.Form):
    login = forms.CharField(label="Login")
    password = forms.CharField(label="Password")

    

products/forms.py
from django import forms
from products.models import Product

class AddProduct(forms.Form):

    title = forms.CharField(label="Наименование")
    price = forms.DecimalField(label="Цена", decimal_places=2, max_digits=6)
    description = forms.CharField(label="Описание")
    quantity = forms.IntegerField(label="В ниличии", min_value=0)

class AllProduct(forms.Form):

    title = forms.CharField(label="Наименование")
    price = forms.DecimalField(label="Цена", decimal_places=2, max_digits=6)


class ProductModelForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ('title', 'price', 'description', 'quantity')

main/views.py
from django.shortcuts import render
from products.models import Product
from main.forms import Login_form
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.utils.http import url_has_allowed_host_and_scheme



def index(request):
    quantity = Product.objects.order_by('-quantity')[:3]

    return render(request, 'main/index.html', locals())


def login_user(request):
    form = Login_form(request.POST)
    # if form.is_valid():
    #     login1 = form.cleaned_data['login']
    #     password = form.cleaned_data['password']
    #     user = authenticate(request, username=login1, password=password)
    #     if user is not None:
    #         login(request, user)
    # way = request.META.get('HTTP_REFERER')

    # if not url_has_allowed_host_and_scheme(url=way, host=request.get_host()):
    #     way = reverse('main:index')
    # return HttpresponseRedirect(way)

def product_detail(request, id):
    product = Product.objects.get(id=id)
    return render(request, '../products/product_detail.html', locals())


def about_us(request):
    return render(request, 'main/about_us.html')

products/views.py
from django.shortcuts import render, redirect
from products.models import Product, Group
from decimal import Decimal
from products.forms import ProductModelForm, AddProduct, AllProduct


def product_group(request):
    group = Group.objects.all()
    return render(request, 'products/product_group.html', locals())


def all_products(request):
    products = Product.objects.all()
    form = AllProduct()
    return render(request, 'products/all_products.html', locals())


def product_detail(request, id):
    product = Product.objects.get(id=id)
    form = ProductModelForm(instance=product)
    return render(request, 'products/product_detail.html', locals())


def add_product(request):
    form = AddProduct()
    return render(request, 'products/add_product.html', locals())


def thanks(request):
    title = request.POST['title']
    price = request.POST['price']
    quantity = request.POST['quantity']
    description = request.POST['description']
    p = Product(title=title, price=price, quantity=quantity, description=description)
    p.save()
    return render(request, 'products/thanks.html', locals())


def edit_product(request, id):
    if request.method == 'GET':
        product = Product.objects.filter(id=id).first()
        form = ProductModelForm(instance=product)
        # product.price = str(product.price)
        # p = Product(title=title, price=price, quantity=quantity, description=description)
        # p.save()
        return render(request, 'products/edit_product.html', locals())
    elif request.method == 'POST':
        title = request.POST['title']
        price = Decimal(request.POST['price'])
        quantity = request.POST['quantity']
        description = request.POST['description']
        # p = Product(
        #     title=title, price=price, 
        #     quantity=quantity, description=description
        # )
        # Product.objects.update(id=id, title='aaaaaaa')
        #p.save()
        p = Product.objects.get(id=id)
        p.title = title
        p.price = price
        p.quantity = quantity
        p.description = description
        p.save()
        return redirect('products:all_products')


def delete_product(request, id):
    if request.method == 'GET':
        product = Product.objects.filter(id=id).first()
        form = ProductModelForm(instance=product)
        # product.price = str(product.price)
        # p = Product(title=title, price=price, quantity=quantity, description=description)
        # p.save()
        return render(request, 'products/delete_product.html', locals())
    elif request.method == 'POST':
        # title = request.POST['title']
        # price = Decimal(request.POST['price'])
        # quantity = request.POST['quantity']
        # description = request.POST['description']
        p = Product.objects.get(id=id)
        p.delete()
        return redirect('products:all_products')
    

main/templates/main/about_us.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <h1>About US</h1>
 
{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
<!--        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>-->
        <span class="fs-4">Online Shop</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
<h1>Base</h1>
        
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:index' %}">Главная</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'products:product_group' %}">Меню товаров</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'products:all_products' %}">Товары</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'products:add_product' %}">Добавить товар</a>        
        <a class="me-3 py-2 text-dark text-decoration-none" href="/">Регистрация</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="/">Корзина</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:about_us' %}">Про нас</a>
        {% if request.user.is_authenticated %}
          <h3>Hello, {{ request.user.username }}</h3>
        {% else %}  
        <form action="{% url 'main:login_user' %}" method="POST"> {% csrf_token %} 
          <table>
            <tr><td>Логин</td><td><input type="text" name="login"></td></tr>
            <tr><td>Пароль</td><td><input type="password" name="password"></td></tr>
            <tr><td><input type="submit" value="Войти"></td><td><input type="submit" value="Зарегестрироваться"></td></tr>
          </table>
      </form>
        {% endif %}
      </nav>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <h1>Главная страница</h1>
    <table border=1>
    <tr>
        <td><h4>Наименование:</h4></td>
        <td>&nbsp</td>
        <td><h4>Цена:</h4></td>
    
    </tr>

    {% for s in quantity %}
    <tr>
        <td><a href="{% url 'products:product_detail' s.id %}">{{ s.title}}</td>
        <td>&nbsp</td>
        <td>{{ s.price}}</td>
    
    </tr>
    {% endfor %}
{% endblock %}

main/templates/main/registration.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <h1>Регистрация</h1>

    <form action="#">
        <p><i>Пожалуйста, заполните форму. Обязательные поля помечены </i><em>*</em></p>
        <fieldset>
          <legend>Контактная информация</legend>
            <label for="name">Имя <em>*</em></label>
            <input id="name"><br>
            <label for="telephone">Телефон</label>
            <input id="telephone"><br>
            <label for="email">Email <em>*</em></label>
            <input id="email"><br>
        </fieldset>
        <fieldset>
          <legend>Персональная информация</legend>
            <label for="age">Возраст<em>*</em></label>
            <input id="age"><br>
            <label for="gender">Пол</label>
            <select id="gender">
              <option value="female">Женщина</option>
              <option value="male">Мужчина</option>
            </select><br>
        </fieldset>
        <p><input type="submit" value="Отправить информацию"></p>
      </form>
 
{% endblock %}

products/templates/products/add_product.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}

    <h2>Добавить товар</h2>


<form action="{% url 'products:thanks' %}" method="post">

    {% csrf_token %}
    
    <table border="1">
        {{ form }}
    </table>
    <button type="submit">Добавить</button>
</form>

{% endblock %}

products/templates/products/all_products.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}

    <form action="">
        <fieldset>
        <label for="name">поиск</label>
        <input id="name">
        <input type="submit" value="поиск">
        </fieldset>
    </form>
    <h2>Все товары</h2>
    <table border="1">
    <tr>
        <td><h4>Наименование:</h4></td>
        <td>&nbsp</td>
        <td><h4>Цена:</h4></td>

    </tr>

    {% for product in products %}
    
        <tr>
            
            <td><a href="{% url 'products:product_detail' product.id %}">{{ product.title}}</a></td>
            <td>&nbsp</td>

            <td><a href="{% url 'products:product_detail' product.id %}">{{ product.price}}</a></td>
        </tr>   
    
    {% endfor %}
    </table>
{% endblock %}

products/templates/products/delete_product.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}

    <h2>Вы ействительно хотите удалить данный продукт!</h2>


<form action="{% url 'products:delete_product' product.id%}" method="POST">
    {% csrf_token %}
    <table border="1">
        {{ form }}
    </table>

    <button type="submit">Удалить</button>
</form>

{% endblock %}

products/templates/products/edit_product.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}

    <h2>Edit product</h2>


<form action="{% url 'products:edit_product' product.id%}" method="POST">
    {% csrf_token %}
    <table border="1">
        {{ form }}
    </table>

    <button type="submit">Edit product</button>
</form>

{% endblock %}

products/templates/products/product_detail.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <h1>Описание товара:</h1>
    <table border="1">
    <tr>
    <td>Название:{{product.title}}</a></td>
    </tr>
    <td>Цена:{{product.price}}</a></td>
    <tr>
    <td>Описание:{{product.description}}</a></td>
</tr>
    <td>Добавлено:{{product.created_at}}</a></td>
    <tr>
    <td>Обновление:{{product.updated_at}}</a></td>
</tr>
    <td>В наличии:{{product.quantity}}</a></td>
</tr>
    </table>
<br>
    <form action="{% url 'products:delete_product' product.id%}" method="">
        <button type="submit"> Delete</button>
    </form>
<br>
    <form action="{% url 'products:edit_product' product.id %}" method="">
        <button type="submit"> Edit product</button>
    </form>
<br>


{% endblock %}

products/templates/products/product_group.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <h1>Product_group</h1>
    <ul>
    {% for g in group %}
    
    <li><a href="/">{{ g.title}}</a></li><br>
    {% endfor %}
    </ul>
{% endblock %}

products/templates/products/thanks.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}

    <h2>Товар добавлен успешно</h2>
    <table border="1">
        <tr>
            <td><h4>Наименование:</h4></td>
            <td>&nbsp</td>
            <td><h4>Цена:</h4></td>
            <td>&nbsp</td>
            <td><h4>Описание:</h4></td>
            <td>&nbsp</td>
            <td><h4>В наличии:</h4></td>
            <td>&nbsp</td>
            <td><h4>Добавлено:</h4></td>
        </tr>
        <tr>
            <td><h4>{{p.title}}</h4></td>
            <td>&nbsp</td>
            <td><h4>{{p.price}}</h4></td>
            <td>&nbsp</td>
            <td><h4>{{p.description}}</h4></td>
            <td>&nbsp</td>
            <td><h4>{{p.quantity}}</h4></td>
            <td>&nbsp</td>
            <td><h4>{{p.created_at}}</h4></td>
        </tr>
    </table>
{% endblock %}